
project_id = "fpwuewixgazaiikqtuwq"

[functions.get-nutrition]
enabled = true
verify_jwt = false
entrypoint = "get-nutrition/index.ts"

[functions.get-openrouter-key]
enabled = true
verify_jwt = false
entrypoint = "get-openrouter-key/index.ts"
