
project_id = "fpwuewixgazaiikqtuwq"

[functions]
[functions.get-nutrition]
verify_jwt = false
entrypoint = "supabase/functions/get-nutrition/index.ts"

[functions.get-openrouter-key]
verify_jwt = false
entrypoint = "supabase/functions/get-openrouter-key/index.ts"
