// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpwuewixgazaiikqtuwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwd3Vld2l4Z2F6YWlpa3F0dXdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzExMTgsImV4cCI6MjA1OTgwNzExOH0.9zU51GU7SPPcLZ5SucSdQlBIy-d8vonbUgjXt-aUXSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);